"""migration test

Revision ID: e9d68afadb55
Revises: 
Create Date: 2025-05-01 17:05:30.174397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9d68afadb55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('otp_secret', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('wall_image_url', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('profile_image_url', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('registerd_wallet', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('registerd_bio', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('wallet_address', sa.String(length=42), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_address', sa.String(length=42), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('wallet_address')

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('wallet_address')
        batch_op.drop_column('registerd_bio')
        batch_op.drop_column('registerd_wallet')
        batch_op.drop_column('profile_image_url')
        batch_op.drop_column('wall_image_url')
        batch_op.drop_column('otp_secret')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
